const CartActionTypes = {
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  CART_SAVE_SHIPPING_ADDRESS: 'CART_SAVE_SHIPPING_ADDRESS',
  CART_SAVE_PAYMENT_METHOD: 'CART_SAVE_PAYMENT_METHOD',
  CART_ITEMS_RESET: 'CART_ITEMS_RESET',
};

export default CartActionTypes;
