const UserActionTypes = {
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  USER_LOGOUT: 'USER_LOGOUT',

  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  USER_DETAILS_REQUEST: 'USER_DETAILS_REQUEST',
  USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
  USER_DETAILS_FAILURE: 'USER_DETAILS_FAILURE',

  USER_UPDATE_PROFILE_REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
  USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
  USER_UPDATE_PROFILE_FAILURE: 'USER_UPDATE_PROFILE_FAILURE',
  USER_UPDATE_PROFILE_RESET: 'USER_UPDATE_PROFILE_RESET',
};

export default UserActionTypes;
