const ProductActionTypes = {
  PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
  PRODUCT_LIST_FAILURE: 'PRODUCT_LIST_FAILURE',

  PRODUCT_DELETE_REQUEST: 'PRODUCT_DELETE_REQUEST',
  PRODUCT_DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
  PRODUCT_DELETE_FAILURE: 'PRODUCT_DELETE_FAILURE',

  PRODUCT_CREATE_REQUEST: 'PRODUCT_CREATE_REQUEST',
  PRODUCT_CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
  PRODUCT_CREATE_FAILURE: 'PRODUCT_CREATE_FAILURE',
  PRODUCT_CREATE_RESET: 'PRODUCT_CREATE_RESET',

  PRODUCT_UPDATE_REQUEST: 'PRODUCT_UPDATE_REQUEST',
  PRODUCT_UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
  PRODUCT_UPDATE_FAILURE: 'PRODUCT_UPDATE_FAILURE',
  PRODUCT_UPDATE_RESET: 'PRODUCT_UPDATE_RESET',

  PRODUCT_CREATE_REVIEW_REQUEST: 'PRODUCT_CREATE_REVIEW_REQUEST',
  PRODUCT_CREATE_REVIEW_SUCCESS: 'PRODUCT_CREATE_REVIEW_SUCCESS',
  PRODUCT_CREATE_REVIEW_FAIL: 'PRODUCT_CREATE_REVIEW_FAIL',
  PRODUCT_CREATE_REVIEW_RESET: 'PRODUCT_CREATE_REVIEW_RESET',

  PRODUCT_TOP_REQUEST: 'PRODUCT_TOP_REQUEST',
  PRODUCT_TOP_SUCCESS: 'PRODUCT_TOP_SUCCESS',
  PRODUCT_TOP_FAIL: 'PRODUCT_TOP_FAIL',
};

export default ProductActionTypes;
