const ProductDetailsTypes = {
  PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
  PRODUCT_DETAILS_FAILURE: 'PRODUCT_DETAILS_FAILURE',
};

export default ProductDetailsTypes;
